[pytest]
# 测试文件位置
testpaths = tests

# 文件命名规则
python_files = test_*.py
python_classes = Test*
python_functions = test_*

# 注册标签
markers =
    smoke: 冒烟测试
    regression: 回归测试

# 默认运行参数：详细模式 + 显示 print 输出
addopts = -v -s --html=reports/report.html --self-contained-html